replicas: 2

image:
  name: nginx
  tag: 1.12

port: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 80m
    memory: 64Mi

env:
  one: two
  foo: bar

annotations:
  ping: pong
  kube: application
