apiVersion: v1
kind: Service # Сервис - это L4-балансировщик, который стоит перед несколькими инстансами приложений
metadata:
  name: ingress-test-1
spec:
  ports:
  - port: 80 # На каком порту сервис принимает запросы.
    targetPort: 80 # Порт в контейнере, куда сервис будет перенаправлять трафик (forward - переотправляет транзитом)
  selector: # Необходим для того, чтобы сервис понимал, на какие именно поды нужно балансировать трафик
    app: my-app-1
  type: ClusterIP
